// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAskp98smXL3cDDAVfWMrr7DP2forU_-ew',
    appId: '1:728783300696:web:6f108506d5fe107510822d',
    messagingSenderId: '728783300696',
    projectId: 'halosmoothie-6a4b6',
    authDomain: 'halosmoothie-6a4b6.firebaseapp.com',
    storageBucket: 'halosmoothie-6a4b6.appspot.com',
    measurementId: 'G-R6DM98T57T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG4REVOQ_LasTAL67y0u6E4Znq98u4Xy0',
    appId: '1:728783300696:android:d46c0a231a2686f710822d',
    messagingSenderId: '728783300696',
    projectId: 'halosmoothie-6a4b6',
    storageBucket: 'halosmoothie-6a4b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEjpypPtkfQRImD1PXIEsc_DSvvY5qPT4',
    appId: '1:728783300696:ios:a9147e86664c50a110822d',
    messagingSenderId: '728783300696',
    projectId: 'halosmoothie-6a4b6',
    storageBucket: 'halosmoothie-6a4b6.appspot.com',
    androidClientId: '728783300696-0ecrku4qh0fl3il08limao30emqrr4n0.apps.googleusercontent.com',
    iosClientId: '728783300696-7j22dgdt67ugatlahts7cp1tj5rq167o.apps.googleusercontent.com',
    iosBundleId: 'com.example.haloSmoothie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEjpypPtkfQRImD1PXIEsc_DSvvY5qPT4',
    appId: '1:728783300696:ios:a9147e86664c50a110822d',
    messagingSenderId: '728783300696',
    projectId: 'halosmoothie-6a4b6',
    storageBucket: 'halosmoothie-6a4b6.appspot.com',
    androidClientId: '728783300696-0ecrku4qh0fl3il08limao30emqrr4n0.apps.googleusercontent.com',
    iosClientId: '728783300696-7j22dgdt67ugatlahts7cp1tj5rq167o.apps.googleusercontent.com',
    iosBundleId: 'com.example.haloSmoothie',
  );
}
